export const AVAILABLE_CHAINS_URL = /* process.env.NEXT_PUBLIC_BACKEND_URL + */ '/bridge/chains'
export const COUNTERPARTY_CHAINS_URL = /* process.env.NEXT_PUBLIC_BACKEND_URL + */ '/bridge/counterpartyChains'
export const BRIDGE_TOKENS_URL = /* process.env.NEXT_PUBLIC_BACKEND_URL + */ '/bridge/bridges'
export const TRANSACTION_HISTORY_URL = /* process.env.NEXT_PUBLIC_BACKEND_URL + */ '/bridge/packet/history'
export const ESTIMATION_URL = /* process.env.NEXT_PUBLIC_BACKEND_URL + */ '/bridge/estimation'
