export const AVAILABLE_CHAINS_URL = '/chains'
export const COUNTERPARTY_CHAINS_URL = '/counterpartyChains'
export const BRIDGE_TOKENS_URL = '/bridges'
export const TRANSACTION_HISTORY_URL = '/history'
export const ESTIMATION_URL = '/estimation'
